### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by raybellwaves** [NCAR/intake-thredds#15]
Looking at https://github.com/NCAR/intake-thredds/blob/master/README.rst#installation

says `pip install intake-thredds`

get

```
(test_env2) ray.bell@administrators-MacBook-Pro test_files % pip install intake-thredds
ERROR: Could not find a version that satisfies the requirement intake-thredds
ERROR: No matching distribution found for intake-thredds
```

**Comment by raybellwaves** [comment]
I see some `intake-siphon` in the docs `https://intake-thredds.readthedocs.io/en/latest/installation.html#installation`. Do it need to released to update the new name?

**Comment by aaronspring** [comment]
You have to install from source. Documentation is still just from template.

**Comment by andersy005** [comment]
I'm currently working on documentation in #19. Once this is merged, we can cut the first official release

**Comment by andersy005** [comment]
@raybellwaves, the first release is live on https://pypi.org/project/intake-thredds/. conda-forge is next...

**Comment by andersy005** [comment]
Closing this as intake-thredds is available from both pypi and conda-forge.
