### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by raybellwaves** [NCAR/intake-thredds#36]
Following https://twitter.com/realaaronspring/status/1401865508585082882?s=20

I wouldn't mind trying the `concat_kwargs` arg.

Any interest in releasing? Happy to help out if needed

**Comment by andersy005** [comment]
Thank you, @raybellwaves! Could we address #37 and #38, and then release a new version? Personally, I am too tight on time this week. So, if someone else wants to take on those two, that would be awesome :)

**Comment by raybellwaves** [comment]
have to fix tests as well

https://github.com/NCAR/intake-thredds/pull/40/checks?check_run_id=2805901382#step:6:31

**Comment by aaronspring** [comment]
Probably the thredds server is just down for a day

**Comment by andersy005** [comment]
The latest release (v2021.6.16) is on PyPI already. It should be on conda-forge shortly.

**Comment by aaronspring** [comment]
thanks @andersy005
