### ISSUE TITLE
if self.progressbar and tqdm is None set progressbar to False

### ISSUE THREAD

**Issue by raybellwaves** [NCAR/intake-thredds#38]
https://github.com/NCAR/intake-thredds/blob/54f1a8d83588b460f35dd99a3d4597176571e0fd/intake_thredds/source.py#L86

Rather than raising a ValueError you could just say `tqdm not installed setting progressbar=False`

**Comment by aaronspring** [comment]
you are welcome to implement this

**Comment by raybellwaves** [comment]
Now I think about this how about just make `tqdm` as a requirement?

It's not uncommon as a requirement `mamba repoquery whoneeds tqdm -c conda-forge`.

Can help slim the code base here.
