### ISSUE TITLE
circle CI fail before and after #3

### ISSUE THREAD

**Issue by aaronspring** [NCAR/intake-thredds#6]
I tried to play around with #3 but I didnt get it running. @andersy005 @martindurant 

Then I saw that circle CI had been failing already before #3 https://app.circleci.com/pipelines/github/NCAR/intake-thredds?branch=master

Maybe we need to use `OpendapSource` from `intake_xarray` instead of `NetcdfSource`? xr.open_dataset() for the underlying links
https://gist.github.com/aaronspring/fa96793675c94504c5158610e4f8e007

BTW: this is a really neat jupyterlab extension for THREDDS: https://github.com/eWaterCycle/jupyterlab_thredds

**Comment by martindurant** [comment]
Can you get it to work with the DAP source?

> this is a really neat jupyterlab extension for THREDDS

I have been aware of this for some time, and thought about what an intake pane in jlab might look like. So far, I have thought it would be exactly the same as the in-notebook GUI, but the ability to paste the currently-selected source into a notebook is nice and worthwhile.

Indeed, it would be great the have catalogue-editing functionality, graphically - but we don't even have the functional API for this really. There is a lot of interesting territory here, for the enthusiastic.

**Comment by aaronspring** [comment]
Which solution do you prefer @andersy005 ? #7 opendap or #8 http. I would just do some timings and decide for the faster...

**Comment by andersy005** [comment]
Not 💯 sure this is relevant, but it appears that the latest versions of libnetcdf has functionality which makes it easy to read netCDF **directly** over HTTP (without needing the netCDF files to be served over an opendap server): https://twitter.com/dopplershift/status/1286415993347047425

Isn't it the case that with http, we would be able to support opendap and any other netCDF files served on any generic HTTP server?

**Comment by martindurant** [comment]
@andersy005 , I think there's discussion of that on intake-xarray (or even xarray); as far as I could gather, it works, but is slow, due to there being a separate request for each piece of metadata and data chunk. I agree that this should be an additional option aside from DAP endpoints. 

I wonder is pangeo should orchestrate on this, since I really don't understand the different engines and metadata services very well - it's all "not zarr" for me :)

**Comment by aaronspring** [comment]
I see intake-thredds as a way to quickly find data. for more frequent analysis I would anyways download the data (to zarr) and then continue...

**Comment by aaronspring** [comment]
# netcdf
![image](https://user-images.githubusercontent.com/12237157/101498913-eec3e980-396c-11eb-8299-c9273cfa61d2.png)

# opendap
![image](https://user-images.githubusercontent.com/12237157/101499282-6134c980-396d-11eb-9550-bb9c93d1d718.png)

# Comparison
so opendap seems faster.

merging #7 ? @andersy005

**Comment by aaronspring** [comment]
or should I try to integrate a keyword that decides whether to take netcdf or opendap? combining both and setting opendap as default? or does this make no sense.

**Comment by andersy005** [comment]
>  I think there's discussion of that on intake-xarray (or even xarray); as far as I could gather, it works, but is slow, due to there being a separate request for each piece of metadata and data chunk. I agree that this should be an additional option aside from DAP endpoints.

👍🏽 

@aaronspring, I vote for going with opendap for the time being (i.e. as the default). We can revisit the generic HTTP later. What do you think?

**Comment by aaronspring** [comment]
I am fine with just merging #7
