### ISSUE TITLE
fails with intake upstream

### ISSUE THREAD

**Issue by aaronspring** [NCAR/intake-thredds#9]
in #7 and #8 

https://github.com/intake/intake/blob/e7a6da73e539461fecc9b717732d9c88552212ae/intake/catalog/base.py#L392

needs to be not a container? EDIT: container='catalog'

**Comment by martindurant** [comment]
Is this intake latest release or master? 

https://github.com/intake/intake/pull/548

**Comment by aaronspring** [comment]
in upstream, intake master is used. the rest of CI uses intake release which works fine.

**Comment by martindurant** [comment]
Following the merger, feel free to prod me here until I get around to fixing versus Intake master (which ought to be released anyhow).
